### ISSUE TITLE
IRC-based Beatmap Status Synchronization

### ISSUE THREAD

**Issue by CloneWith** [CloneWith/osu#25]
Based on the following idea:

![Chat](https://github.com/user-attachments/assets/e3c3a1fb-d9c0-46db-892b-6a1e16f060fa)

This is to somehow "integrate" with juroe in an indirect way, in terms of basic beatmap mark information.

## Tasks

- [x] Fetch chat messages
- [x] Filtering out useful commands
- [x] Beatmap control (distinguish from automatic map selecting, *partial*)
- [x] Sync board layout by reading from chessboard message

**Comment by CloneWith** [comment]
The filtering function based on user IDs still needs to be tested, here as a memo for us ;)

**Comment by CloneWith** [comment]
> [x] Sync board layout by reading from chessboard message

This is nearly resolved in #35, you could have a try at it.
